services:
  - type: web
    name: qa-ghost-shopper
    env: python
    buildCommand: bash render-build.sh
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
